version: '3.9'
services:
  db:
    image: mysql:8.0.37 # RDSのMySQLバージョンに合わせる
    container_name: gourmet-app-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: gourmet-app
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - gourmet-app-mysql-volume:/var/lib/mysql
    networks:
      gourmet-app-network:

# ホスト上にDocker管理のボリュームを作成(名前付きボリューム)
volumes:
  gourmet-app-mysql-volume:

# ネットワークを作成
networks:
  gourmet-app-network:
    driver: bridge