services:
  db:
    image: mysql:8.0.37 # RDSのMySQLバージョンに合わせる
    container_name: gourmet-app-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: gourmet-app
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - gourmet-app-mysql-volume:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    networks:
      backend:
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -ppassword

  test-app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: test-app
    volumes:
      - .:/liff-app-backend
    working_dir: /liff-app-backend
    environment:
      - DATABASE_URL=mysql://user:password@db/my_database
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:8081"
    tty: true

# ホスト上にDocker管理のボリュームを作成(名前付きボリューム)
volumes:
  gourmet-app-mysql-volume:

# ネットワークを作成
networks:
  backend:
    name: gourmet-app-network
    driver: bridge