# パスパラメータをキャメルケースに統一して。
openapi: 3.0.1
info:
  version: 1.0.5
  title: life アプリ API
tags:
  - name: 飲食店
  - name: コメント
  - name: お気に入り
  - name: ジャンル
  - name: 画像
security:
  - Bearer: [ ]
paths:
  /restaurant:
    get:
      tags:
        - 飲食店
      summary: 一覧
      description: 飲食店の一覧を取得する
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: number
                      description: "ID"
                      example: 1
                    name:
                      type: string
                      description: "店名"
                      example: "なか卯"
                    nearest_station:
                      type: string
                      description: "最寄り駅"
                      example: "新橋"
                    genre:
                      type: string
                      description: "ジャンル"
                      example: "1,2,3"
                    image_url:
                      type: string
                      description: 画像URL
                      example: 'https://~'
                    comment:
                      type: string
                      description: 登録者コメント
                      example: '登録者コメント'
                    is_favorite:
                      type: boolean
                      description: お気に入りフラグ
                      example: true
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
    post:
      tags:
        - 飲食店
      summary: 登録
      description: "飲食店の登録する"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 店名
                  example: 'なか卯'
                nearest_station:
                  type: string
                  description: 最寄り駅
                  example: '新橋'
                genre:
                  type: array
                  description: ジャンル
                  example: '1,2,3'
                website_url:
                  type: string
                  description: 外部サイトURL
                  example: 'htttps://~'
                comment:
                  type: string
                  description: 飲食店登録者コメント
                  example: '登録者コメント'
              required:
                - name
                - nearest_station
                - genre
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: "number"
                    description: "ID"
                    example: 1
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
  /restaurant/{id}:
    get:
      tags:
        - 飲食店
      summary: 詳細
      description: "飲食店の詳細情報を取得"
      parameters:
        - in: path
          name: "id"
          description: "ID"
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: "number"
                    description: "ID"
                    example: 1
                  name:
                    type: "string"
                    description: "飲食店名"
                    example: "なか卯"
                  nearest_station:
                    type: string
                    description: "最寄り駅"
                    example: "新橋"
                  genre:
                    type: string
                    description: "ジャンル"
                    example: "1,2,3"
                  user_name:
                    type: string
                    description: "更新ユーザー名"
                    example: "あだち"
                  website_url:
                    type: string
                    description: 外部サイトURL
                    example: 'htttps://~'
                  images:
                    type: "array"
                    items:
                      type: "string"
                      description: "スライドする画像のurl返す"
                    example:
                      - "スライドする画像のurl返す1"
                      - "スライドする画像のurl返す2"
                      - "スライドする画像のurl返す3"
                      - "スライドする画像のurl返す4"
                      - "スライドする画像のurl返す5"
                  comment:
                    type: string
                    description: 飲食店登録者コメント
                    example: '登録者コメント'
                  replies:
                    type: "array"
                    description: "飲食店に対するユーザーの返信"
                    items:
                      type: "object"
                      properties:
                        id:
                          type: "number"
                          description: "返信ID"
                          example: 1
                        user_name:
                          type: "string"
                          description: "ユーザー名"
                          example: "三浦"
                        comment:
                          type: string
                          description: "コメント"
                          example: "確かにおいしかったです。"
                        created_at:
                          type: string
                          description: "作成日"
                          example: "2024-08-02 20:04:34"
                  created_at:
                    type: string
                    description: "作成日"
                    example: "2024-08-02 20:04:34"
                  updated_at:
                    type: string
                    description: "更新日"
                    example: "2024-08-02 21:04:34"
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
    put:
      tags:
        - 飲食店
      summary: 編集
      description: "飲食店の編集する"
      parameters:
        - in: path
          name: "id"
          description: "ID"
          required: true
          schema:
            type: number
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 店名
                  example: 'なか卯'
                nearest_station:
                  type: string
                  description: 最寄り駅
                  example: '新橋'
                genre:
                  type: string
                  description: ジャンル
                  example: '1,2,3'
                website_url:
                  type: string
                  description: 外部サイトURL
                  example: 'htttps://~'
                comment:
                  type: string
                  description: 飲食店登録者コメント
                  example: '登録者コメント'
                user_name:
                  type: string
                  description: 更新ユーザー名
                  example: ”あだち”
              required:
                - name
                - nearest_station
                - genre
                - user_name
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: "number"
                    description: "ID"
                    example: 1
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
    delete:
      tags:
        - 飲食店
      summary: 削除
      description: "飲食店の情報を削除"
      parameters:
        - in: path
          name: "ID"
          description: "飲食店ID"
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: successful operation
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
  /restaurant/{restaurant_id}/reply:
    post:
      tags:
        - コメント
      summary: コメント投稿
      description: "コメントを投稿する"
      parameters:
        - in: path
          name: "restaurant_id"
          description: "飲食店ID"
          required: true
          schema:
            type: number
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  description: コメント
                  example: 'ユーザーのコメント'
              required:
                - comment
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  replies:
                    type: "array"
                    description: "飲食店に対するユーザーの返信"
                    items:
                      type: "object"
                      properties:
                        user_name:
                          type: "string"
                          description: "ユーザー名"
                          example: "三浦"
                        comment:
                          type: string
                          description: "コメント"
                          example: "確かにおいしかったです。"
                        created_at:
                          type: string
                          description: "作成日"
                          example: "2024-08-02 20:04:34"
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
  /restaurant/{restaurant_id}/reply/{reply_id}:
    put:
      tags:
        - コメント
      summary: コメント編集
      description: "コメントを編集する"
      parameters:
        - in: path
          name: "restaurant_id"
          description: "飲食店ID"
          required: true
          schema:
            type: number
            example: 1
        - in: path
          name: "reply_id"
          description: "コメントID"
          required: true
          schema:
            type: number
            example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  description: コメント
                  example: 'ユーザーのコメント'
              required:
                - comment
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: integer
                    description: コメントid
                    example: 1
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
    delete:
      tags:
        - コメント
      summary: コメント削除
      description: "コメントを削除する"
      parameters:
        - in: path
          name: "restaurant_id"
          description: "飲食店ID"
          required: true
          schema:
            type: number
            example: 1
        - in: path
          name: "reply_id"
          description: "コメントID"
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: successful operation
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
  /restaurant/{restaurant_id}/favorite:
    post:
      tags:
        - お気に入り
      summary: お気に入り登録
      description: "お気に入りの登録を行う"
      parameters:
        - in: path
          name: "restaurant_id"
          description: "飲食店ID"
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  restaurant_id:
                    type: "integer"
                    description: "お気に入り登録された飲食店ID"
                    example: 1
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
    delete:
      tags:
        - お気に入り
      summary: お気に入り解除
      description: "お気に入りの解除を行う"
      parameters:
        - in: path
          name: "restaurant_id"
          description: "飲食店ID"
          required: true
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  restaurant_id:
                    type: "integer"
                    description: "お気に入り解除された飲食店ID"
                    example: 1
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
  /genre:
    get:
      tags:
        - ジャンル
      summary: 一覧
      description: ジャンルの一覧を取得する
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: number
                      description: "ID"
                      example: 1
                    name:
                      type: string
                      description: "ジャンル名"
                      example: "和食"
        '400':
          $ref: "#/components/responses/400Error"
        '401':
          $ref: "#/components/responses/401Error"
        '500':
          $ref: "#/components/responses/500Error"
components:
  securitySchemes:
    Bearer:
      type: http
      name: Authorization
      in: header
      scheme: bearer
      description: アクセストークン
  schemas:
    Error:
      description: エラー
      type: object
      required:
        - message
      properties:
        message:
          description: エラーメッセージ
          type: string
          example: エラーメッセージ内容を記載する
  responses:
    400Error:
      description: '400エラー'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    401Error:
      description: '401エラー'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    500Error:
      description: '500エラー'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
