AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  グルメLIFFアプリのバックエンド用AWS SAMテンプレート
  以下のリソースを管理する。
    - API Gateway
    - Lambda Function
    - CloudWatch Logs

Globals:
  Function:
    Timeout: 29
    MemorySize: 128
    Tracing: Active
    Runtime: python3.11
    Environment:
      Variables:
        STAGE: !Ref STAGE
  Api:
    TracingEnabled: true

Parameters:
  STAGE:
    Description: 環境名
    Type: String
    Default: local
    AllowedValues:
      - prod
      - local
  IS_TEST:
    Description: テスト実行フラグ
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Resources:
  #################### API Gateway ####################
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: gourmet-liff-app-api-gw
      EndpointConfiguration: REGIONAL
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'POST, GET, OPTIONS, DELETE, PATCH, PUT'"
        AllowCredentials: true

  #################### Lambda Function ####################
  ReviewPostFunction:
    Type: AWS::Serverless::Function
    Description: レビュー投稿API
    Properties:
      FunctionName: review-post
      Role: arn:aws:iam::328715503375:role/iife-app-sam
      CodeUri: ./app
      Handler: main.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /review
            Method: post
            RestApiId: !Ref APIGateway
