AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  グルメLIFFアプリのバックエンド用AWS SAMテンプレート
  以下のリソースを管理する。
    - API Gateway
    - Lambda Function
    - CloudWatch Logs

Globals:
  Function:
    Timeout: 29
    MemorySize: 128
    Tracing: Active
    Runtime: python3.11
  Api:
    TracingEnabled: true

Resources:
  #################### API Gateway ####################
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: gourmet-liff-app-api-gw
      EndpointConfiguration: REGIONAL
      StageName: prod
      Cors:
        AllowOrigin: "'https://d36s9gm15va9cu.cloudfront.net'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'POST, GET, OPTIONS, DELETE, PATCH, PUT'"
        AllowCredentials: true

  #################### Lambda Function ####################
  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: life-app-list
      Role: arn:aws:iam::328715503375:role/iife-app-sam
      CodeUri: list/
      Handler: app.lambda_handler
      Architectures:
      - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/list
            Method: get
            RestApiId: !Ref APIGateway

  DetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: life-app-detail
      CodeUri: detail/
      Handler: app.lambda_handler
      Architectures:
      - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/detail
            Method: get
            RestApiId: !Ref APIGateway

  #################### CloudWatch Logs ####################
  ListFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ListFunction}
      RetentionInDays: 14

  DetailFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DetailFunction}
      RetentionInDays: 14