AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  グルメLIFFアプリのバックエンド用AWS SAMテンプレート
  以下のリソースを管理する。
    - API Gateway
    - Lambda Function
    - CloudWatch Logs

Globals:
  Function:
    Timeout: 29
    MemorySize: 128
    Tracing: Active
    Runtime: python3.11
  Api:
    TracingEnabled: true

Resources:
  #################### API Gateway ####################
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: gourmet-liff-app-api-gw
      EndpointConfiguration: REGIONAL
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'POST, GET, OPTIONS, DELETE, PATCH, PUT'"
        AllowCredentials: true

  #################### Lambda Function ####################
  # APIの作成例
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world
      Role: arn:aws:iam::328715503375:role/iife-app-sam
      CodeUri: ./app
      Handler: app.lambda_handler
      Architectures:
        - arm64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
            RestApiId: !Ref APIGateway
