name: pytest

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v3

      # コンテナをセットアップ
      - name: Start Docker containers
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for services to start
        run: |
          sleep 15

      # テストを実行
      - name: Run tests with pytest
        run: |
          docker compose exec -T test-app poetry run pytest --disable-warnings -q -s

      # テスト後にコンテナを停止
      - name: Stop Docker containers
        run: |
          docker compose -f docker-compose.yml down
